name: workflow
on:
  - push

jobs:
  commit-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Restore cache
        uses: actions/cache@v1
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-${{ github.ref }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ github.ref }}-
            ${{ runner.os }}-
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Commit lint
        run: yarn commitlint

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'

      - name: Build
        env:
          MDBOOK_OUTPUT__HTML__GOOGLE_ANALYTICS: ${{ secrets.MDBOOK_OUTPUT__HTML__GOOGLE_ANALYTICS }}
        run: |
          mdbook test
          mdbook build

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: book
          path: book

  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs:
      - commit-lint
      - build
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v1
        with:
          name: book

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book
          cname: ${{ secrets.DOMAIN }}

